### ISSUE TITLE
No module named bg_atlasapi

### ISSUE THREAD

**Issue by PetrDvoracek** [ArtemKirsanov/BlenderBrain#2]
# System
OS: Linux, Manjaro 23.0.0 Uranos
Blender version: 3.6

# Problem
After installation, I am not able to enable the add-on _3D View: BlenderBrain_. I am getting error
```
Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/.config/blender/3.6/scripts/addons/BlenderBrain/__init__.py", line 51, in <module>
    import bg_atlasapi
ModuleNotFoundError: No module named 'bg_atlasapi'

```

# Reason
Module `bg_atlasapi` should be automatically installed [using subprocess during registration of your BlenderBrain module](https://github.com/ArtemKirsanov/BlenderBrain/blob/f3817f1ee8c3af77aeaf40632897efce825606d8/BlenderBrain/__init__.py#L44), but this attempt fails, since blender uses system interpreter on Linux Blender is not allowed to install anything to system interpreter on Linux.

How I realized that Blender uses system Python? Typed this into Python console in Blender:
```
>>> import sys
>>> sys.executable
'/usr/bin/python3.11'
```

# Safe Solution
Install the necessary packages with root privilege to the system Python. **OR** Change Blender's Python interpreter on Linux. Unfortunately, I can not install packages easily to the system interpreter on manjaro **AND**  it is not clear to me how to change the Blender's interpreter because I did not find a link in blender application files which would point to `/usr/bin/python3.11` and could be directly changed to point somewhere else (e.g. conda environment).

# Unsafe Solution

**Do not do this if you are a beginner, or you do not know what you are doing! It could potentially lead to unexpected breaking of the system!**

Create a new environment with conda `conda create -n blender python=3.11.3`. Version should be changed according to the output of `sys.version` in Blender. Activate this environment with `conda activate blender`, install required module with `pip install bg_altasapi`. 

Now comes the trick - find where your conda env installed the library (`~/anaconda3/envs/blender/lib/python3.11/site-packages/` on my machine) and link libs located there to your system python (which Blender uses) with `ln -s ~/anaconda3/envs/blender/lib/python3.11/site-packages/* /usr/lib/python3.11/site-packages`. 

If you install any other packages, just repeat linking the libs as described in previous paragraph.

With the unsafe solution, I was able to enable the add-on.

**Comment by javismiles** [comment]
I have tried the safe solution, installing all on the default root python but after restart I keep getting same error: No module named 'bg_atlasapi'  , help please

**Comment by nperessini** [comment]
I figured it out just with
`pip install bg-atlasapi==0.1.0`
on the Blender's Python

**Comment by jensen-facts** [comment]
mf you are the goat, thank u so much
